/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
    },

    onsendNewPage: function() {
        if(!Ext.getCmp('stationPanel'))
        Ext.create('MyApp.view.stationPanel', {fullscreen: true});
        Ext.getCmp('stationPanel').items.items[2].items.items[0].setData({"bnTitle":"whitehall, Parliment Street Greatet London","bnDes":"1.2 miles east of current location","NoOfCy":"8","NoOfP":"2","Data1":"Data Published by TFL 3 minutes ago","Data2":"Last checked 30s ago"});
        // Ext.getCmp('stationPanel').items.items[3].items.items[0].setData({});
        // Ext.getCmp('stationPanel').items.items[4].items.items[0].setData({});
        Ext.getCmp('stationPanel').show({ type: 'slide',duration: 500,direction:'left'});
    }

});